services:
  back:
    build:
      context: ./back
    tty: true
    env_file:
      - ./back/.env.example
    volumes:
      - ./back:/dotslife
    depends_on:
      - db
    ports:
      - "5050:5050"
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dotslife
      TZ: "Asia/Tokyo"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$MYSQL_ROOT_PASSWORD",
        ]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  db_data:
